### ISSUE TITLE
[VASL] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2680] opened 2023-05-22 18:28 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [49329 bytes](https://vassalengine.org/files/gh/4e3c57d7795d54ef0ec28b2efc7f6495547a289d) |

<pre>Attempting to add overlay Wd1 on 24I6 for scenario WCW10 after having added the other overlays before in the order specified on the scenario card. Overlays have been added after previously changing Terrain to PTO with Lt. Jungle.

For questions, can be contacted via GameSquad forum - von Marwitz

VASL v6.6.6 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by derimmer** [comment] 2023-06-02 19:30
Transferred to VASL1406

All of these ExecutionExceptions in VASL (between issues 2640 to 2680) are caused by a problem at Underlay.java line 112 in VASL. I have fixed the problem and trapped a similar error should it occur. This will be in VASL6.6.7.

**Closed as completed by derimmer** 2023-06-02 19:30 UTC
Labels: ABR

**Comment by uckelman** [comment] 2023-06-02 19:35
When can we expect 6.6.7? It would be nice to stop seeing these errors.

**Comment by derimmer** [comment] 2023-06-02 22:39
You and me both. I am going to release a beta version with the fix within the week but I am not sure that will make much difference. 

The official release is planned for November but if that feels like a month too far, I can probably move it up to September.

**Comment by uckelman** [comment] 2023-06-03 10:49
Could you do a release now with just the fix for this bug, but not the other 6.6.7 changes?

**Comment by derimmer** [comment] 2023-06-04 11:30
Our user community doesn't like that. I have had to do it a couple of times recently and the response was not positive.

I will get the beta out shortly. I will post some additional messages about the fix to the overlay bug and I will follow up quicker with anyone who posts a bug report to you.

**Comment by uckelman** [comment] 2023-06-04 12:44
I find it hard to fathom that you'd get a negative response worth worrying about from fixing a problem.

If you put out a bugfix release, no one's forced to upgrade, those who wish to may, and anyone who doesn't want to upgrade but still complains about the bug can justifiably be told to pound sand.

**Comment by derimmer** [comment] 2023-06-06 20:18
The beta is out. If it doesn't stop the flow of Exception reports then I will put out bugfix release.
