### ISSUE TITLE
[Operation Mercury: The Invasion of Crete] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutableProperty.getPropertyValue()" because "this.globalProperty" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2607] opened 2022-04-28 19:04 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | neil@neilandnicky.plus.com |
| Error Log | [50000 bytes](https://vassalengine.org/files/gh/4fe6e0db24e71757660723e4dbc8da6c784b89fc) |

<pre>On the Charts having moved from one tab to another.

Operation Mercury: The Invasion of Crete v2.3 3.6.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutableProperty.getPropertyValue()" because "this.globalProperty" is null
 at tdc.TdcScenarioOptions$BooleanOption.createConfigurer(TdcScenarioOptions.java:358)
 at tdc.TdcScenarioOptions$BasicOption.buildControls(TdcScenarioOptions.java:340)
 at tdc.TdcScenarioOptions$BasicOption.getControls(TdcScenarioOptions.java:334)
 at tdc.TdcScenarioOptions.getComponent(TdcScenarioOptions.java:154)
</pre>

**Comment by BrentEaston** [comment] 2022-05-01 11:44
Duplicate of #2600

**Closed as completed by BrentEaston** 2022-05-01 11:44 UTC
Labels: bug, GTS Series
