### ISSUE TITLE
Problem via custom code (VASL.counters.Concealable) - [VASL] IllegalArgumentException: Width (-1) and height (-1) must be > 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2424] opened 2021-06-28 15:16 UTC
| Bugzilla |  |
|----------|----------|
| ID | BZ14144 |
| Reported | 2021-02-27 18:38:00 +0100 |
| Modified | 2021-03-16 01:07:14 +0100 |
| Product | VASL |
| Component | Counter |
| Version | 6.6.1 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | 6.0.0 |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |
| CC | brian@brianreynolds.net |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/12792) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-02-27 18:38:00 +0100 text/plain 16577 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-02-27 18:38:43 +0100
<pre>VASL v6.6.1 3.5.3

java.lang.IllegalArgumentException: Width (-1) and height (-1) must be > 0
 at java.desktop/java.awt.image.SampleModel.<init>(SampleModel.java:126)
 at java.desktop/java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:140)
 at java.desktop/java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
 at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:642)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-02-27 18:38:44 +0100
<pre>Created attachment 12792
the errorLog</pre>

**Comment by derimmer** [comment] 2021-08-03 21:20
I believe that this is the same error as #2475. Is there a way that I can mark them duplicates? I can't seem to find it.

**Comment by derimmer** [comment] 2021-08-05 00:02
Both this and #2475 were reported by users using VASL6.6.1. This particular bug was captured in VASL issue #905 and fixed in VASL via PR 906. It should not occur in VASL6.6.2 and no such errors have been reported so far. 

It involved users opening a saved game which required concealment counters provided by extensions that they did not have loaded (Polish and Swedish Volunteers).

**Closed as completed by derimmer** 2021-08-05 00:02 UTC
Labels: VASL

**Comment by uckelman** [comment] 2021-08-24 19:49
> I believe that this is the same error as #2475. Is there a way that I can mark them duplicates? I can't seem to find it.

The way to mark duplicates here is by commenting "Duplicate of #NNNN" and then clicking "Comment and Close".

**Comment by derimmer** [comment] 2021-08-24 21:11
Duplicate of #2475.
