### ISSUE TITLE
ABR: [VASL] NoSuchMethodError: 'void VASL.build.module.map.ASLBrokenFinder.findBrokenPiece()'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/modules#2481] opened 2021-06-28 15:19 UTC
| Bugzilla |  |
|----------|----------|
| ID | BZ14446 |
| Reported | 2021-05-02 21:42:00 +0200 |
| Modified | 2021-05-02 22:14:02 +0200 |
| Product | VASL |
| Component | All |
| Version | 6.6.2 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Doug Rimmer](mailto:dougrimmer@rogers.com) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/12957) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-02 21:42:00 +0200 text/plain 26757 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-02 21:42:15 +0200
<pre>VASL v6.6.2 3.5.5

java.lang.NoSuchMethodError: 'void VASL.build.module.map.ASLBrokenFinder.findBrokenPiece()'
 at VASL.build.module.map.QCMod$1.actionPerformed(QCMod.java:127)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-05-02 21:42:15 +0200
<pre>Created attachment 12957
the errorLog</pre>

**Comment by derimmer** [comment] 2021-11-30 19:10
Duplicate of #2580

**Closed by derimmer** 2021-11-30 19:10 UTC
Labels: VASL
